/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package junit5;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void sumTest() {
        assertEquals(100,Integer.sum(40,60));
    }
}
